### ISSUE TITLE
Alternate VFS question

### ISSUE THREAD

**Issue by marzhall** [google/crfs#11]
Howdy!

Just a thought, in case the option wasn't explored or considered -
have you considered using a [9p](https://en.wikipedia.org/wiki/9P_(protocol)) virtual filesystem implementation instead of FUSE?

I ask because it supports partial file reads, has a driver in the linux kernel, and and is network mountable - so machines who want to mount a container can just `mount <networkip> /containers` or the like, assuming the server is posting the 9p FS on a port.

It may let you cut out the http requests, depending on how easy it is to access containers without going through the registry directly. You'd also only need to install software on the registry server - nothing would be needed client-side, since linux already has the driver.

Just a thought from taking a glance - my apologies if it's not applicable, and thanks for the project!

**Comment by bradfitz** [comment]
I'm not sure what that'd buy us, honestly.

The whole point of this is to put something client-side so I *don't* need to modify the registry (gcr.io) and install software there.

FUSE also supports partial file reads and we're already using that and efficiently batching minimal HTTP requests.

**Comment by marzhall** [comment]
Ah, gotcha. I missed that there was a desire to avoid software on the server-side, and had thought from the readme that the HTML requests were considered a bit of a speed concern - but it makes sense that if you're batching them, it should work out. Thanks!
