### ISSUE TITLE
comment on CVMFS

### ISSUE THREAD

**Issue by rptaylor** [google/crfs#13]
FYI maybe you have already heard about it before, but this seems similar to using CVMFS for container distribution.

General information on CVMFS:
https://cvmfs.readthedocs.io/en/stable/
https://cernvm.cern.ch/portal/filesystem
https://github.com/cvmfs/cvmfs

Information about loading docker images on demand from CVMFS:
https://cvmfs.readthedocs.io/en/stable/cpt-graphdriver.html

Information about automatically converting container images and publishing them to CVMFS (with DUCC)
https://cvmfs.readthedocs.io/en/stable/cpt-ducc.html

**Comment by bradfitz** [comment]
Thanks, I hadn't seen that before.

I see it's alike in that they both make outbound HTTP requests to fault in data as needed. I'm guessing it's different in that they have a specialized server, where CRFS's goal is to use existing Container Registry servers, and still be compatible with normal "docker pull" etc workflows.

**Comment by rptaylor** [comment]
Yes, CVMFS has a hierarchical stratum model of servers (a single authoritative stratum 0, and multiple stratum 1 servers replicate from it). So this handles the load balancing and distribution part, like a CDN. The same infrastructure can be used to serve repositories of container images as well as repositories of any other content/software. The stratum servers are based on Apache httpd.

**Comment by rptaylor** [comment]
When using CVMFS, DUCC (the last URL in the post) is sort of like a shim layer that takes the images from the existing container registry servers and automates publishing them onto CVMFS.

**Comment by Leo88999** [comment]
hello im a blogger too...i found out your blog on google,its a nice blog, full of information and i like to read your article, keep work.. would you mind to visit my blog too and give some suggestion to improve my blog.. this is my blog address : 
<a href="https://angkawiki.com/">mix parlay bet</a>
<a href="https://angkawiki.com/">permainan mix parlay</a>
<a href="https://angkawiki.com/">mix parlay</a>
<a href="https://kalebsu.wixsite.com/agentogelonline/post/how-to-mix-parlay-bets">mix parlay bet</a>
<a href="http://beritabet.mystrikingly.com/">mix parlay </a>
<a href="https://angelinewijaya-xnzs.envatosites.com/">mix parlay bet</a>
thanks you.

**Comment by rptaylor** [comment]
Now the containerd remote snapshotter exists and can be used by CVMFS and other remote filesystems.

**Comment by OMiOhMi** [comment]
Omg

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
